name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#F7AA00&palette=github-dark
            dist/github-snake-dark.svg?color_snake=#F7AA00&palette=github-dark

      - name: Commit snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 update snake"
          add: "dist/*"
